const home = require('../support/elements/home.json')

describe('Home tests', () => {
    it('Check items on the home page', () => {
        cy.visit('/')
        cy.validateLayout(false, false)
        cy.get(home.hero_section_div).should('be.visible').highlight()
        cy.get(home.main_title_h1).should('be.visible').highlight()
        cy.get(home.main_description_p).should('be.visible').highlight()
        cy.get(home.start_now_a).should('be.visible').highlight()
        cy.get(home.downloads_title_h5).should('be.visible').highlight()
        cy.get(home.downloads_description_p).should('be.visible').highlight()
        cy.get(home.downloads_open_a).should('be.visible').highlight()
        cy.get(home.tutorials_title_h5).should('be.visible').highlight()
        cy.get(home.tutorials_description_p).should('be.visible').highlight()
        cy.get(home.tutorials_open_a).should('be.visible').highlight()
        cy.get(home.faq_title_h5).should('be.visible').highlight()
        cy.get(home.faq_description_p).should('be.visible').highlight()
        cy.get(home.faq_open_a).should('be.visible').highlight()
        cy.get(home.quiz_title_h5).should('be.visible').highlight()
        cy.get(home.quiz_description_p).should('be.visible').highlight()
        cy.get(home.quiz_open_a).should('be.visible').highlight()
        cy.get(home.useful_contents_title_h5).should('be.visible').highlight()
        cy.get(home.useful_contents_description_p).should('be.visible').highlight()
        cy.get(home.useful_contents_open_a).should('be.visible').highlight()
        cy.get(home.useful_tools_title_h5).should('be.visible').highlight()
        cy.get(home.useful_tools_description_p).should('be.visible').highlight()
        cy.get(home.useful_tools_open_a).should('be.visible').highlight()
    })
})