name: End-to-End Tests

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:

  build:
    name: Build Site

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24.13.0
          cache: npm

      - run: npm ci

      - name: Build
        run: npm run build
        env:
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}
          API_BASE_URL: ${{ secrets.API_BASE_URL_DEV }}
          API_KEY: ${{ secrets.API_KEY }}

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: public-site
          path: public

  e2e:
    name: Cypress (${{ matrix.runner }}/4)

    needs: build

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        runner: [1, 2, 3, 4]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24.13.0
          cache: npm

      - run: npm ci

      - uses: actions/download-artifact@v4
        with:
          name: public-site
          path: public

      - name: Run Cypress
        run: npm run e2e:serve
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}

          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}
          API_BASE_URL: ${{ secrets.API_BASE_URL_DEV }}
          API_KEY: ${{ secrets.API_KEY }}

      - name: Upload Cypress Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-${{ matrix.runner }}
          path: |
            cypress/screenshots
            cypress/videos
          if-no-files-found: ignore